kind: pipeline
type: docker
name: Build & Publish

steps:

- name: docker build
  image: plugins/docker
  environment:
    DOCKER_BUILDKIT: 1
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: 
      from_secret: docker_reponame
    tags: latest

trigger:
  branch:
  - master